$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot

$required = @(
  "AGENTS.md",
  "PLANS.md",
  "docs/audit/app-dev-audit-closeout.md",
  ".github/workflows/app-dev-validation.yml",
  ".codex/config.toml",
  ".codex/rules/default.rules",
  ".codex/hooks/pre-command.ps1",
  ".codex/hooks/post-edit.ps1",
  ".codex/hooks/verify-before-finish.ps1",
  "standards/command-workflow-contract.md",
  "standards/stack.md",
  "standards/workspace.md",
  "standards/scripting.md",
  "standards/codex-capabilities.md",
  "standards/spec-driven-workflow.md",
  "standards/adaptive-layouts.md",
  "standards/testing.md",
  "standards/security.md",
  ".agents/README.md",
  ".agents/skills/README.md",
  ".agents/commands/specify.md",
  ".agents/commands/plan.md",
  ".agents/commands/tasks.md",
  ".agents/commands/implement.md",
  ".agents/commands/analyze.md",
  ".agents/commands/verify.md",
  ".agents/commands/release-readiness.md",
  ".agents/skills/cross-platform-app-workflow/SKILL.md",
  ".agents/skills/ui-change-workflow/SKILL.md",
  ".agents/skills/data-change-workflow/SKILL.md",
  ".agents/skills/mobile-validation-workflow/SKILL.md",
  ".agents/skills/release-readiness-workflow/SKILL.md",
  ".agents/skills/cross-platform-app-workflow/agents/openai.yaml",
  ".agents/skills/cross-platform-app-workflow/references/stack.md",
  ".agents/skills/cross-platform-app-workflow/references/module-contract.md",
  ".agents/skills/cross-platform-app-workflow/references/adaptive-layouts.md",
  ".agents/skills/cross-platform-app-workflow/references/qa-gates.md",
  ".agents/skills/cross-platform-app-workflow/references/spec-driven-workflow.md",
  "scripts/create-app.ps1",
  "scripts/new-spec.ps1",
  "scripts/check-spec-artifacts.ps1",
  "scripts/get-workflow-obligations.ps1",
  "scripts/validate-workflow-receipts.ps1",
  "scripts/verify-app.ps1",
  "scripts/test-hooks.ps1",
  "scripts/test-workflow-enforcement.ps1",
  "scripts/test-workspace.ps1",
  "scripts/validate-codex-assets.ps1",
  "scripts/scan-secrets.ps1",
  "scripts/export-workspace.ps1",
  "templates/PLAN.template.md",
  "templates/spec-workflow/spec.template.md",
  "templates/spec-workflow/tasks.template.md",
  "templates/spec-workflow/checklist.template.md",
  "templates/spec-workflow/workflow-receipts.template.md",
  "templates/spec-workflow/converge.template.md",
  "templates/common/.github/workflows/verify.yml",
  "templates/react-vite-capacitor/package.json",
  "templates/react-vite-capacitor/.github/workflows/verify.yml",
  "templates/react-vite-capacitor/capacitor.config.ts",
  "templates/react-vite-capacitor/tailwind.config.ts",
  "templates/react-vite-capacitor/postcss.config.js",
  "templates/react-vite-capacitor/components.json",
  "templates/react-vite-capacitor/scripts/add-native-platforms.ps1",
  "templates/react-vite-capacitor/src/app/routes.tsx",
  "templates/react-vite-capacitor/src/lib/env.ts",
  "templates/react-vite-capacitor/src/lib/supabase.ts",
  "templates/react-vite-capacitor/supabase/README.md",
  "templates/react-vite-capacitor/supabase/migrations/001_template_foundation.sql",
  "templates/react-vite-capacitor/src/vite-env.d.ts",
  "templates/react-vite-capacitor/src/components/layout/SettingsLayout.tsx",
  "templates/react-vite-capacitor/src/modules/settings/routes/SettingsRoute.tsx",
  "templates/react-vite-capacitor/src/modules/dashboard/index.ts",
  "templates/react-vite-capacitor/src/components/state/EmptyState.tsx",
  "templates/react-vite-capacitor/src/components/state/LoadingState.tsx",
  "templates/react-vite-capacitor/src/components/state/ErrorState.tsx",
  "templates/next-web-app/package.json",
  "templates/next-web-app/app/layout.tsx",
  "templates/next-web-app/app/page.tsx",
  "templates/next-web-app/tsconfig.json",
  "templates/next-web-app/eslint.config.js",
  "templates/next-web-app/tests/smoke.test.ts",
  "templates/expo-native-app/package.json",
  "templates/expo-native-app/app.json",
  "templates/expo-native-app/App.tsx",
  "templates/expo-native-app/tsconfig.json",
  "templates/expo-native-app/jest.config.js",
  "templates/expo-native-app/tests/App.test.tsx",
  "projects"
)

$missing = @()
foreach ($item in $required) {
  $path = Join-Path $root $item
  if (-not (Test-Path $path)) {
    $missing += $item
  }
}

if ($missing.Count -gt 0) {
  Write-Error ("Missing required workspace files: " + ($missing -join ", "))
}

Write-Host "app-dev workspace check passed: $root"
